# Passing a list

In [7]:
def square(lst):
    squares = []    
    for num in lst:
        squares.append(num**2)        
    return squares

In [8]:
square([3,4,6,7,6,8])

[9, 16, 36, 49, 36, 64]

In [9]:
square([13,14,16,17,16,18])

[169, 196, 256, 289, 256, 324]

In [24]:
students={
          "st1":{'name':'Nasir','roll':123,'age':21,'course':'python'},
          "st2":{'name':'Asad','roll':124,'age':20,'course':'mobile'},
          "st3":{'name':'Yasir','roll':125,'age':30,'course':'python'},
          "st4":{'name':'Umer','roll':126,'age':19,'course':'web'},
          "st5":{'name':'faisal','roll':127,'age':20,'course':'mobile'},
          "st6":{'name':'tahir','roll':128,'age':41,'course':'python'}
         }

In [25]:
def add_email_id(dic):
    for key in dic:
        dic[key]['email'] = f"{dic[key]['name']}{dic[key]['roll']}@gmail.com"
    return dic

In [26]:
print(add_email_id(students))

{'st1': {'name': 'Nasir', 'roll': 123, 'age': 21, 'course': 'python', 'email': 'Nasir123@gmail.com'}, 'st2': {'name': 'Asad', 'roll': 124, 'age': 20, 'course': 'mobile', 'email': 'Asad124@gmail.com'}, 'st3': {'name': 'Yasir', 'roll': 125, 'age': 30, 'course': 'python', 'email': 'Yasir125@gmail.com'}, 'st4': {'name': 'Umer', 'roll': 126, 'age': 19, 'course': 'web', 'email': 'Umer126@gmail.com'}, 'st5': {'name': 'faisal', 'roll': 127, 'age': 20, 'course': 'mobile', 'email': 'faisal127@gmail.com'}, 'st6': {'name': 'tahir', 'roll': 128, 'age': 41, 'course': 'python', 'email': 'tahir128@gmail.com'}}


{
'st1': {'name': 'Nasir', 'roll': 123, 'age': 21, 'course': 'python', 'email': 'Nasir123@gmail.com'}, 
'st2': {'name': 'Asad', 'roll': 124, 'age': 20, 'course': 'mobile', 'email': 'Asad124@gmail.com'}, 
'st3': {'name': 'Yasir', 'roll': 125, 'age': 30, 'course': 'python', 'email': 'Yasir125@gmail.com'}, 
'st4': {'name': 'Umer', 'roll': 126, 'age': 19, 'course': 'web', 'email': 'Umer126@gmail.com'},
'st5': {'name': 'faisal', 'roll': 127, 'age': 20, 'course': 'mobile', 'email': 'faisal127@gmail.com'}, 
'st6': {'name': 'tahir', 'roll': 128, 'age': 41, 'course': 'python', 'email': 'tahir128@gmail.com'}
}

print(-2//4)
# -0.5
#

        0.9 >>> round >>> next smallest int >>1
        10.4 >>>> round>>> prev big int >>10
        
            -1.5,-1, -0.5, 0, 0.5, 1, 1.5

# write a function that accepts a list of numbers between 1000,3000 return all those numbers whose every digit is even. 

In [38]:
def alldigitseven(lst):
    allevens=[]
    for num in lst:
        num =str(num) 
        if int(num[0])%2==0:  
            if int(num[1])%2==0:
                if int(num[2])%2==0:
                    if int(num[3])%2==0:
                        allevens.append(int(num))
    return allevens

In [39]:
nums = list(range(1000,3001))

In [40]:
alldigitseven(nums)

[2000,
 2002,
 2004,
 2006,
 2008,
 2020,
 2022,
 2024,
 2026,
 2028,
 2040,
 2042,
 2044,
 2046,
 2048,
 2060,
 2062,
 2064,
 2066,
 2068,
 2080,
 2082,
 2084,
 2086,
 2088,
 2200,
 2202,
 2204,
 2206,
 2208,
 2220,
 2222,
 2224,
 2226,
 2228,
 2240,
 2242,
 2244,
 2246,
 2248,
 2260,
 2262,
 2264,
 2266,
 2268,
 2280,
 2282,
 2284,
 2286,
 2288,
 2400,
 2402,
 2404,
 2406,
 2408,
 2420,
 2422,
 2424,
 2426,
 2428,
 2440,
 2442,
 2444,
 2446,
 2448,
 2460,
 2462,
 2464,
 2466,
 2468,
 2480,
 2482,
 2484,
 2486,
 2488,
 2600,
 2602,
 2604,
 2606,
 2608,
 2620,
 2622,
 2624,
 2626,
 2628,
 2640,
 2642,
 2644,
 2646,
 2648,
 2660,
 2662,
 2664,
 2666,
 2668,
 2680,
 2682,
 2684,
 2686,
 2688,
 2800,
 2802,
 2804,
 2806,
 2808,
 2820,
 2822,
 2824,
 2826,
 2828,
 2840,
 2842,
 2844,
 2846,
 2848,
 2860,
 2862,
 2864,
 2866,
 2868,
 2880,
 2882,
 2884,
 2886,
 2888]

In [43]:
num = 2288
num = str(num)

In [46]:
int(num[0])%2

0

You need to write a code which accepts a sequence of comma separated 4 digit binary numbers 

as its input and then check whether they are divisible by 5 or not.

The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:

0100,0011,1010,1001

Then the output should be:

1010

Reference: https://www.datacamp.com/community/tutorials/python-data-type-conversion

https://stackoverflow.com/questions/21765779/converting-binary-to-decimal-integer-output

In [51]:
int('101010',2)

42

In [52]:
bin(42)

'0b101010'

In [63]:
binary_nums = input("Enter 4 comma separated binary digits of size 4").split(',')
multiple_of_5=[]
for b in binary_nums:
    if int(b,2)%5==0:
        multiple_of_5.append({int(b,2):b})
multiple_of_5


Enter 4 comma separated binary digits of size 40100,0011,1010,1001


[{10: '1010'}]

In [ ]:
b_num = input("Enter 4 digit comma separated binary number")